name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
    steps:
      - uses: zendesk/checkout@v3
      - name: Set up Ruby
        uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: zendesk/checkout@v3
      - name: Set up Ruby
        uses: zendesk/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - run: bundle exec rake standard
